# Use postgres/example user/password credentials
version: '3.1'

services:
  postgres_db:
    image: postgres
    container_name: pg
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432

  pg_admin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: username
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
      - 5050:80
